### ISSUE TITLE
Cannot install just typing 'install ECS' or 'install MVVM'

### ISSUE THREAD

**Issue by sdotyxz** [uFrame/ALLINONE#5]

**Comment by sdotyxz** [comment]
when i install in this order, i could build without error.
install nitreo/csharp60
install nitreo/UniRx
install uFrame/CORE
install uFrame/MVVM or install uFrame/ECS
I think dependency is not enough in github's metadata when it comes to running 'install uFrame/ECS'.

And also it would be better if Koinonia Plugin could provide & operation, so that we could just type 'install nitreo/csharp60 & install nitreo/UniRx &... ' so that everything could be pipelined.

**Comment by ZimM-LostPolygon** [comment]
In it's current form, using Koinonia today does more harm than good. Instructions are outdated anyway and should be updated. Git works just fine.
