### ISSUE TITLE
Can't seem to clone due to permission issues.

### ISSUE THREAD

**Issue by mgmhunt** [uFrame/ALLINONE#9]
`Cloning into '/Volumes/Scrappy/__SYSTEM/Git Remotes/uFrame/uFrame.Complete/uFrame.**Architect**'...
warning: templates not found /usr/local/git/share/git-core/templates
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:uFrame/uFrame.Architect.git' into submodule path '/Volumes/Scrappy/__SYSTEM/Git Remotes/uFrame/uFrame.Complete/uFrame.Architect' failed
Failed to clone 'uFrame.Complete/uFrame.Architect'. Retry scheduled
Cloning into '/Volumes/Scrappy/__SYSTEM/Git Remotes/uFrame/uFrame.Complete/uFrame.**Designer**'...
warning: templates not found /usr/local/git/share/git-core/templates
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

etc. etc. etc.

**Comment by mgmhunt** [comment]
Just downloaded each submodule individually for the meantime.

**Comment by ZimM-LostPolygon** [comment]
@mgmhunt 
Supposedly, this is fixed now.
